"""fix_user_roles_unique_constraint

Revision ID: fb1597937ba5
Revises: fix_user_roles_constraint
Create Date: 2025-12-15 07:21:39.825463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1597937ba5'
down_revision: Union[str, None] = 'fix_user_roles_constraint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

